---
brew_packages:
  - autojump
  - bat
  - btop
  - direnv
  - fzf
  - fzf-make
  - gh
  - git-delta
  - git-extras
  - git-lfs
  - hatch
  - hub
  - jq
  - just
  - jesseduffield/lazydocker/lazydocker
  - lazygit
  - Adembc/homebrew-tap/lazyssh
  - mas
  - mermaid-cli
  - micro
  - moor
  - nmap
  - node
  - pipx
  - ripgrep
  - shellcheck
  - tree

brew_cask_packages:
  - google-chrome
  - hammerspoon
  - iterm2
  - macdown
  - pycharm-ce
  - signal
  - spotify
  - sublime-text

mas_apps:
  - name: Amphetamine
    id: 937984704
  - name: iStat Menus
    id: 1319778037
  - name: Tailscale
    id: 1475387142

mas_upgrade_all_apps: false
