---
# Version of the release to install
starship_version: 1.24.2

# Architecture of the static binary
starship_arch: "{{ ansible_architecture }}"

# URL to the archive of the release to install
starship_download: "https://github.com/starship/starship/releases/download/v{{ starship_version }}/starship-{{ starship_arch }}-unknown-linux-musl.tar.gz"

# Directory in which to install the binary
starship_install_directory: "/usr/local/bin"

# User who will own the binary file
starship_owner: root

# Group who will own the binary file
starship_group: wheel
