docker_dir: "{{ ansible_facts['user_dir'] }}/docker"

caddyfile_dest: "{{ docker_dir }}/caddy/Caddyfile"

autoplex_repo_dest: "{{ docker_dir }}/autoplex"
autoplex_repo_url: https://github.com/danielmmetz/autoplex.git
autoplex_repo_branch: master

pyautoplex_repo_dest: "{{ docker_dir }}/pyautoplex"
pyautoplex_repo_url: git@github.com:connormason/pyautoplex.git
pyautoplex_repo_branch: main

homeassistant_repo_dest: "{{ docker_dir }}/homeassistant"
homeassistant_repo_url: git@github.com:connormason/homeassistant.git
homeassistant_repo_branch: nas_bringup                                  # TODO: change to master after merge
