hammerspoon_config_dir: "{{ ansible_facts['user_dir'] }}/.hammerspoon"
hammerspoon_config_src: "{{ dotfiles_home }}/roles/hammerspoon/files/init.lua"
hammerspoon_config_dest: "{{ hammerspoon_config_dir }}/init.lua"
